### ISSUE TITLE
Update for latest libbsd?

### ISSUE THREAD

**Issue by guillemj** [aperezdc/signify#16]
Hi!

libbsd upstream here. :) Latest releases should have native musl support, so you could switch to use that and remove the patching required. In addition latest releases also include expicit_bzero support so you might be able to drop the local embedded copy. HTH,

In addition I'd recommend using the libbsd-overlay, which makes it possible use unmodified upstream BSD code, as the headers are exposed in their normal locations, #include <stdlib.h> instead of #include <bsd/stdlib.h>, you can see more info in «man libbsd».

**Comment by aperezdc** [comment]
@guillemj Thanks a lot for the heads up, it is great to know that you are supporting Musl now, and certainly will simplify things quite a bit. I'll take the overlay headers mode, but I guess probably I will have to keep the local modifications while some GNU/Linux distributions still ship older versions.

**Comment by aperezdc** [comment]
@guillemj I have successfully been able to make builds for a couple of architectures successfully using Musl 0.9.1; it's great to not have to carry the Musl patches anymore. Thanks again for your input!

**Comment by frink** [comment]
@guillemj @aperezdc 

Sorry to report that I'm having issues building MUSL=1 EXTRA_LDFLAGS='-static'... 

It complains about pthread_mutex_lock and unlock as undefined references. I'm on Arch Linux with a fresh everything. libgcc_eh.c and arc4random.c seem to be the offending files...

Kinda stumped as to why it works with dynamic linking and dies bloody with static linking.

Any ideas on your end?

**Comment by frink** [comment]
On further investigation, this seems to be a problem regardless of the MUSL flag.
