### ISSUE TITLE
Differences to minisign

### ISSUE THREAD

**Issue by martinberg212** [aperezdc/signify#20]
Could someone please give a short summary about what differs between signify and minisign? https://github.com/jedisct1/minisign

Based on the description they both do exactly the same which makes it kinda hard to decide which to use.

Thank you for any explanation.

**Comment by aperezdc** [comment]
Both programs are largely equivalent, have a similar feature set, but signatures generated by one *cannot* be verified with the other (and vice versa). The main differences are:

- Minisign stores private keys in a different format, see the [Compatibility with OpenBSD signify](https://jedisct1.github.io/minisign/#compatibility-with-openbsd-signify) section in the Minisig website for details.
- Minisign has a `-H` command line switch which generates signatures that Signify cannot read.
- The Signify code comes directly from the OpenBSD repository, with minor changes to make it portable to other systems, while Minisig seems to have been implemented from scratch.

The following blog post has a more in-depth comparison: https://hlischt.com/signify-minisign

**Comment by martinberg212** [comment]
Thank you for the reply :)
