### ISSUE TITLE
Incorrect pledge(2) signature

### ISSUE THREAD

**Issue by saghul** [aperezdc/signify#21]
The current signature for pledge(2) in https://github.com/aperezdc/signify/blob/master/compat.h#L36 seems to match that of OpenBSD 6.1: https://man.openbsd.org/OpenBSD-6.1/pledge.2 but it got changed in 6.3: https://man.openbsd.org/OpenBSD-6.3/pledge.2 It's listed in the changelog here: https://www.openbsd.org/63.html

**Comment by aperezdc** [comment]
Good catch, thanks @saghul for reporting this.

**Comment by saghul** [comment]
That was quick! Cheers!
