### ISSUE TITLE
Sign release tarballs with the program itself

### ISSUE THREAD

**Issue by a-vrma** [aperezdc/signify#31]
I think it would be great to be "self-hosting" in that way. In not unrelated news, the key you are using to sign the release tarballs seems to have expired in May (after you signed so it isn't your fault):

```
gpg: Signature made Fri 06 Mar 2020 06:18:22 PM EST
gpg:                using DSA key 5AA3BC334FD7E3369E7C77B291C559DBE4C9123B
gpg: Good signature from "Adrián Pérez de Castro <aperez@igalia.com>" [expired]
gpg:                 aka "Adrián Pérez de Castro (personal) <adrian@perezdecastro.org>" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: 5AA3 BC33 4FD7 E336 9E7C  77B2 91C5 59DB E4C9 123B
```

**Comment by aperezdc** [comment]
@a-vrma One doubt I have been having which has prevented me from using Signify itself for releases is how to revoke keys. In OpenBSD what they do is that each release includes the keys that will be used for the next, so old keys are automatically “expired” as they will be unused. But that does not seem too practical to do for standalone releases of Signify.

I think for now I will use always the same Signify key to sign releases, and sign the public key with my PGP key :thinking:

**Comment by aperezdc** [comment]
Oh, and my PGP key had indeed expired, I have renewed it a while ago and re-uploaded it to [keys.openpgp.org](https://keys.openpgp.org/). The following should get you an updated copy:

```sh
gpg --keyserver hkps://keys.openpgp.org --recv-keys 5AA3BC334FD7E3369E7C77B291C559DBE4C9123B
```

**Comment by aperezdc** [comment]
Well, I have just went ahead and released [v30](https://github.com/aperezdc/signify/releases/tag/v30) a moment ago, which is signed with Signify itself :tada: 

I'll leave this issue open until I add some notes in the `README.md` file about how releases are signed.

**Comment by aperezdc** [comment]
@a-vrma Thanks for the suggestion, by the way!
